version: '0.01'
services:
  nginx:
    image: nginx:alpine
    ports:
      - 81:80
    volumes:
      - ./clientAdmin/dist:/usr/share/nginx/html
      - ./server-conf/nginx.conf:/etc/nginx/conf.d/default.conf